import type { CaseTypeDefinition } from './schema.js';

/**
 * The case types the platform ships with.
 *
 * Every one of these is data. None of them is referenced by name anywhere in
 * the engine: the workflow, eligibility, evidence and review behaviour all come
 * from the structure below. A firm can edit any of it, and a new solution -
 * statutory or commercial - is a new entry rather than a release.
 *
 * IMPORTANT ABOUT THE THRESHOLDS
 * ------------------------------
 * Statutory limits (DRO debt and asset ceilings, surplus income limits, Scottish
 * MAP bands, bankruptcy fees) change by regulation. The figures below are
 * starting configuration carrying the authority they came from, and every one
 * is editable by the firm without a deployment. A firm must verify them against
 * the current regulations before relying on them; the platform records which
 * version was in force when a case was evaluated, which is the property that
 * actually matters for a later file review.
 */

const CONSENT_AND_IDENTITY = [
  {
    key: 'consent.processing', label: 'Consent to process personal data', kind: 'consent' as const,
    description: 'Recorded with the lawful basis and the wording the client saw.', blocking: true,
  },
  {
    key: 'identity.verified', label: 'Identity verified', kind: 'identity' as const,
    description: 'Electronic or documentary verification of the client.', blocking: true,
  },
  {
    key: 'vulnerability.assessed', label: 'Vulnerability assessment addressed', kind: 'vulnerability-assessment' as const,
    description: 'Assessed against the four FG21/1 drivers, including a recorded "no indicators identified".',
    blocking: true,
  },
];

const FINANCIAL_EVIDENCE = [
  {
    key: 'sfs.complete', label: 'Standard Financial Statement complete', kind: 'financial-statement' as const,
    description: 'A current statement with income, expenditure and household composition.', blocking: true,
  },
  {
    key: 'debts.captured', label: 'Debts and creditors captured', kind: 'declaration' as const,
    description: 'All known debts recorded with their provenance.', blocking: true,
  },
];

function commonStages(adviceStage: string) {
  return [
    { key: 'referral', name: 'Referral', order: 0, requiredEvidence: [], allowedNext: ['onboarding', 'closed'],
      description: 'Case received from an introducer, campaign or direct enquiry.', slaHours: 24,
      isAdvicePoint: false, isTerminal: false },
    { key: 'onboarding', name: 'Onboarding', order: 1,
      requiredEvidence: ['consent.processing', 'identity.verified'],
      allowedNext: ['fact-find', 'closed'], description: 'Consent, identity and initial contact.',
      slaHours: 72, isAdvicePoint: false, isTerminal: false },
    { key: 'fact-find', name: 'Fact find', order: 2,
      requiredEvidence: ['vulnerability.assessed', 'sfs.complete', 'debts.captured'],
      allowedNext: [adviceStage, 'closed'],
      description: 'Financial position, household circumstances and vulnerability.',
      slaHours: 120, isAdvicePoint: false, isTerminal: false },
  ];
}

export const CASE_TYPE_TEMPLATES: readonly CaseTypeDefinition[] = [
  // -------------------------------------------------------------------------
  {
    key: 'dmp',
    name: 'Debt Management Plan',
    description: 'An informal arrangement to repay non-priority debts at an affordable rate.',
    category: 'debt-management',
    jurisdictions: ['england-wales', 'scotland', 'northern-ireland'],
    authority: 'FCA CONC 8',
    referenceFormat: 'DMP-{SEQ}',
    hasPaymentPlan: true,
    requiresCreditorApproval: false,
    reviewCadence: { everyMonths: 12, description: 'Annual review of income, expenditure and balances.' },
    stages: [
      ...commonStages('advice'),
      { key: 'advice', name: 'Advice', order: 3, requiredEvidence: [],
        allowedNext: ['setup', 'closed'], description: 'Regulated advice recorded by a competent adviser.',
        slaHours: 48, isAdvicePoint: true, isTerminal: false },
      { key: 'setup', name: 'Set up', order: 4, requiredEvidence: ['payment.mandate'],
        allowedNext: ['live', 'closed'], description: 'Creditor notification and payment arrangement.',
        slaHours: 168, isAdvicePoint: false, isTerminal: false },
      { key: 'live', name: 'Live', order: 5, requiredEvidence: [],
        allowedNext: ['review', 'arrears', 'closed'], description: 'Plan in payment.',
        isAdvicePoint: false, isTerminal: false },
      { key: 'review', name: 'Annual review', order: 6, requiredEvidence: ['sfs.complete'],
        allowedNext: ['live', 'arrears', 'closed'], description: 'Reassessment of affordability.',
        slaHours: 336, isAdvicePoint: false, isTerminal: false },
      { key: 'arrears', name: 'Arrears', order: 7, requiredEvidence: [],
        allowedNext: ['live', 'review', 'closed'], description: 'Payments missed; forbearance being applied.',
        slaHours: 72, isAdvicePoint: false, isTerminal: false },
      { key: 'closed', name: 'Closed', order: 8, requiredEvidence: [], allowedNext: [],
        description: 'Completed, withdrawn or transferred.', isAdvicePoint: false, isTerminal: true },
    ],
    evidence: [
      ...CONSENT_AND_IDENTITY, ...FINANCIAL_EVIDENCE,
      { key: 'payment.mandate', label: 'Payment mandate in place', kind: 'payment-mandate',
        description: 'Direct debit or standing order authorised by the client.', blocking: true },
    ],
    eligibilityRules: [
      { key: 'has-surplus', description: 'A DMP needs a sustainable monthly contribution.',
        requirement: 'Monthly surplus of at least £1',
        when: { gte: [{ fact: 'affordability.sustainablePaymentPence' }, { const: 100 }] },
        failMessage: 'There is no sustainable surplus, so a DMP would not be affordable. Consider a statutory solution or a token payment arrangement.',
        severity: 'blocking', authority: 'FCA CONC 8.3' },
      { key: 'has-non-priority-debt', description: 'A DMP addresses non-priority debt.',
        requirement: 'At least one non-priority debt',
        when: { gte: [{ fact: 'debt.nonPriorityCount' }, { const: 1 }] },
        failMessage: 'There are no non-priority debts for a DMP to address.', severity: 'blocking' },
      { key: 'priority-debts-addressed', description: 'Priority debts must be handled first.',
        requirement: 'Priority arrears are being addressed',
        when: { or: [{ eq: [{ fact: 'debt.priorityArrearsPence' }, { const: 0 }] },
                     { eq: [{ fact: 'case.priorityDebtsAddressed' }, { const: true }] }] },
        failMessage: 'Priority arrears must be addressed before non-priority debts. Deal with rent, mortgage, council tax and fuel first.',
        severity: 'warning', authority: 'FCA CONC 8.3' },
    ],
    complianceRules: [
      { key: 'annual-review-current', description: 'Reviews must not fall overdue.',
        requirement: 'Annual review completed within the last 13 months',
        when: { lte: [{ fact: 'case.monthsSinceLastReview' }, { const: 13 }] },
        failMessage: 'The annual review is overdue.', severity: 'warning' },
    ],
  },

  // -------------------------------------------------------------------------
  {
    key: 'iva',
    name: 'Individual Voluntary Arrangement',
    description: 'A binding arrangement with creditors, supervised by an insolvency practitioner.',
    category: 'insolvency',
    jurisdictions: ['england-wales', 'northern-ireland'],
    authority: 'Insolvency Act 1986 Part VIII; IVA Protocol 2025',
    referenceFormat: 'IVA-{SEQ}',
    hasPaymentPlan: true,
    requiresCreditorApproval: true,
    reviewCadence: { everyMonths: 12, description: 'Annual review required under the arrangement.' },
    stages: [
      ...commonStages('advice'),
      { key: 'advice', name: 'Advice', order: 3, requiredEvidence: [],
        allowedNext: ['proposal', 'closed'], description: 'Regulated advice recorded by a competent adviser.',
        slaHours: 48, isAdvicePoint: true, isTerminal: false },
      { key: 'proposal', name: 'Proposal', order: 4,
        requiredEvidence: ['proposal.signed', 'ip.appointed'],
        allowedNext: ['creditor-vote', 'closed'], description: 'Proposal prepared and signed; nominee appointed.',
        slaHours: 336, isAdvicePoint: false, isTerminal: false },
      { key: 'creditor-vote', name: 'Creditor decision', order: 5, requiredEvidence: [],
        allowedNext: ['live', 'closed'], description: 'Creditors vote on the proposal.',
        slaHours: 336, isAdvicePoint: false, isTerminal: false },
      { key: 'live', name: 'In arrangement', order: 6, requiredEvidence: [],
        allowedNext: ['review', 'arrears', 'variation', 'closed'], description: 'Arrangement approved and in payment.',
        isAdvicePoint: false, isTerminal: false },
      { key: 'review', name: 'Annual review', order: 7, requiredEvidence: ['sfs.complete'],
        allowedNext: ['live', 'variation', 'arrears', 'closed'], description: 'Annual review of the arrangement.',
        slaHours: 336, isAdvicePoint: false, isTerminal: false },
      { key: 'variation', name: 'Variation', order: 8, requiredEvidence: [],
        allowedNext: ['live', 'closed'], description: 'A change to the arrangement requiring creditor agreement.',
        isAdvicePoint: false, isTerminal: false },
      { key: 'arrears', name: 'Arrears', order: 9, requiredEvidence: [],
        allowedNext: ['live', 'variation', 'closed'], description: 'Payments missed; breach process engaged.',
        slaHours: 72, isAdvicePoint: false, isTerminal: false },
      { key: 'closed', name: 'Closed', order: 10, requiredEvidence: [], allowedNext: [],
        description: 'Completed, failed, revoked or withdrawn.', isAdvicePoint: false, isTerminal: true },
    ],
    evidence: [
      ...CONSENT_AND_IDENTITY, ...FINANCIAL_EVIDENCE,
      { key: 'proposal.signed', label: 'Proposal signed by the client', kind: 'signature',
        description: 'Client signature on the proposal to creditors.', blocking: true },
      { key: 'ip.appointed', label: 'Insolvency practitioner appointed as nominee', kind: 'declaration',
        description: 'Named practitioner with a current appointment.', blocking: true },
    ],
    eligibilityRules: [
      { key: 'minimum-debt', description: 'Firms generally require a minimum qualifying debt for an IVA to be viable.',
        requirement: 'Qualifying debt of at least £6,000',
        when: { gte: [{ fact: 'debt.qualifyingPence' }, { const: 600000 }] },
        failMessage: 'Qualifying debt is below the level at which an IVA is normally viable. Consider a DRO, a DMP or bankruptcy.',
        severity: 'blocking', authority: 'Firm policy, informed by IVA Protocol 2025' },
      { key: 'minimum-creditors', description: 'An arrangement needs a creditor body that can vote.',
        requirement: 'At least two creditors',
        when: { gte: [{ fact: 'debt.creditorCount' }, { const: 2 }] },
        failMessage: 'An IVA normally requires more than one creditor.', severity: 'blocking' },
      { key: 'sustainable-contribution', description: 'The arrangement must be payable for its full term.',
        requirement: 'Sustainable monthly contribution of at least £80',
        when: { gte: [{ fact: 'affordability.sustainablePaymentPence' }, { const: 8000 }] },
        failMessage: 'The available contribution is unlikely to sustain an IVA. Consider a DRO or bankruptcy.',
        severity: 'blocking', authority: 'Firm policy' },
      { key: 'no-recent-breathing-space', description: 'IVA Protocol 2025 flags a Breathing Space in the previous 24 months.',
        requirement: 'No Breathing Space registration in the last 24 months',
        when: { or: [{ isNull: { fact: 'history.monthsSinceBreathingSpace' } },
                     { gt: [{ fact: 'history.monthsSinceBreathingSpace' }, { const: 24 }] }] },
        failMessage: 'A Breathing Space was registered within the last 24 months. This must be disclosed and explained in the proposal.',
        severity: 'warning', authority: 'IVA Protocol 2025' },
      { key: 'prior-insolvency-disclosed', description: 'Any previous DRO or bankruptcy must be disclosed.',
        requirement: 'Previous DRO or bankruptcy disclosed where applicable',
        when: { or: [{ eq: [{ fact: 'history.hasPriorInsolvency' }, { const: false }] },
                     { eq: [{ fact: 'history.priorInsolvencyDisclosed' }, { const: true }] }] },
        failMessage: 'A previous DRO or bankruptcy has not been disclosed on the file.',
        severity: 'blocking', authority: 'IVA Protocol 2025' },
    ],
    complianceRules: [
      { key: 'annual-review-current', description: 'The arrangement requires an annual review.',
        requirement: 'Annual review completed within the last 13 months',
        when: { lte: [{ fact: 'case.monthsSinceLastReview' }, { const: 13 }] },
        failMessage: 'The annual review is overdue.', severity: 'blocking' },
    ],
  },

  // -------------------------------------------------------------------------
  {
    key: 'dro',
    name: 'Debt Relief Order',
    description: 'A statutory debt write-off for people with low debt, low assets and low surplus income.',
    category: 'insolvency',
    jurisdictions: ['england-wales'],
    authority: 'Insolvency Act 1986 Part 7A. Thresholds set by regulation - verify against current limits.',
    referenceFormat: 'DRO-{SEQ}',
    hasPaymentPlan: false,
    requiresCreditorApproval: false,
    reviewCadence: { everyMonths: null, description: 'No periodic review; moratorium runs for 12 months.' },
    stages: [
      ...commonStages('advice'),
      { key: 'advice', name: 'Advice', order: 3, requiredEvidence: [],
        allowedNext: ['application', 'closed'], description: 'Regulated advice recorded by a competent adviser.',
        slaHours: 48, isAdvicePoint: true, isTerminal: false },
      { key: 'application', name: 'Application', order: 4,
        requiredEvidence: ['dro.approved-intermediary', 'application.signed'],
        allowedNext: ['moratorium', 'closed'], description: 'Application submitted through an approved intermediary.',
        slaHours: 168, isAdvicePoint: false, isTerminal: false },
      { key: 'moratorium', name: 'Moratorium', order: 5, requiredEvidence: [],
        allowedNext: ['closed'], description: 'Order granted; moratorium period running.',
        isAdvicePoint: false, isTerminal: false },
      { key: 'closed', name: 'Closed', order: 6, requiredEvidence: [], allowedNext: [],
        description: 'Discharged, revoked or refused.', isAdvicePoint: false, isTerminal: true },
    ],
    evidence: [
      ...CONSENT_AND_IDENTITY, ...FINANCIAL_EVIDENCE,
      { key: 'dro.approved-intermediary', label: 'Approved intermediary confirmed', kind: 'declaration',
        description: 'A DRO application must be made through an approved intermediary.', blocking: true },
      { key: 'application.signed', label: 'Application approved by the client', kind: 'signature',
        description: 'Client confirmation of the application contents.', blocking: true },
    ],
    eligibilityRules: [
      { key: 'debt-ceiling', description: 'Total qualifying debt must not exceed the statutory ceiling.',
        requirement: 'Qualifying debt at or below the current DRO debt limit',
        when: { lte: [{ fact: 'debt.qualifyingPence' }, { fact: 'config.droDebtLimitPence' }] },
        failMessage: 'Qualifying debt exceeds the DRO limit. Consider an IVA or bankruptcy.',
        severity: 'blocking', authority: 'Debt Relief Orders (Designated Competent Authorities) regulations - verify current limit' },
      { key: 'asset-ceiling', description: 'Total assets must not exceed the statutory ceiling.',
        requirement: 'Assets at or below the current DRO asset limit',
        when: { lte: [{ fact: 'assets.totalPence' }, { fact: 'config.droAssetLimitPence' }] },
        failMessage: 'Assets exceed the DRO limit.', severity: 'blocking' },
      { key: 'surplus-ceiling', description: 'Surplus income must not exceed the statutory ceiling.',
        requirement: 'Monthly surplus at or below the current DRO surplus limit',
        when: { lte: [{ fact: 'sfs.surplusPence' }, { fact: 'config.droSurplusLimitPence' }] },
        failMessage: 'Surplus income exceeds the DRO limit. Consider a DMP or an IVA.', severity: 'blocking' },
      { key: 'vehicle-value', description: 'A motor vehicle above the threshold disqualifies unless adapted for disability.',
        requirement: 'No motor vehicle above the current value limit',
        when: { or: [{ lte: [{ fact: 'assets.vehicleValuePence' }, { fact: 'config.droVehicleLimitPence' }] },
                     { eq: [{ fact: 'assets.vehicleAdaptedForDisability' }, { const: true }] }] },
        failMessage: 'The client owns a vehicle valued above the DRO limit.', severity: 'blocking' },
      { key: 'no-active-insolvency', description: 'A DRO cannot run alongside another procedure.',
        requirement: 'No active bankruptcy, IVA or DRO',
        when: { eq: [{ fact: 'history.hasActiveInsolvency' }, { const: false }] },
        failMessage: 'The client is already subject to an insolvency procedure.', severity: 'blocking' },
    ],
    complianceRules: [],
  },

  // -------------------------------------------------------------------------
  {
    key: 'bankruptcy',
    name: 'Bankruptcy',
    description: 'Application to the adjudicator for a bankruptcy order.',
    category: 'insolvency',
    jurisdictions: ['england-wales'],
    authority: 'Insolvency Act 1986. Application fee set by regulation - verify current amount.',
    referenceFormat: 'BKY-{SEQ}',
    hasPaymentPlan: false,
    requiresCreditorApproval: false,
    reviewCadence: { everyMonths: null, description: 'No periodic review.' },
    stages: [
      ...commonStages('advice'),
      { key: 'advice', name: 'Advice', order: 3, requiredEvidence: [],
        allowedNext: ['application', 'closed'], description: 'Regulated advice recorded by a competent adviser.',
        slaHours: 48, isAdvicePoint: true, isTerminal: false },
      { key: 'application', name: 'Application', order: 4, requiredEvidence: ['bankruptcy.fee-arranged'],
        allowedNext: ['order-made', 'closed'], description: 'Application to the adjudicator.',
        slaHours: 336, isAdvicePoint: false, isTerminal: false },
      { key: 'order-made', name: 'Order made', order: 5, requiredEvidence: [],
        allowedNext: ['closed'], description: 'Bankruptcy order in force.',
        isAdvicePoint: false, isTerminal: false },
      { key: 'closed', name: 'Closed', order: 6, requiredEvidence: [], allowedNext: [],
        description: 'Discharged or application refused.', isAdvicePoint: false, isTerminal: true },
    ],
    evidence: [
      ...CONSENT_AND_IDENTITY, ...FINANCIAL_EVIDENCE,
      { key: 'bankruptcy.fee-arranged', label: 'Application fee arranged', kind: 'declaration',
        description: 'The client has the fee available or a payment plan for it.', blocking: true },
    ],
    eligibilityRules: [
      { key: 'no-active-insolvency', description: 'Cannot apply while subject to another procedure.',
        requirement: 'No active insolvency procedure',
        when: { eq: [{ fact: 'history.hasActiveInsolvency' }, { const: false }] },
        failMessage: 'The client is already subject to an insolvency procedure.', severity: 'blocking' },
      { key: 'fee-affordable', description: 'The application fee must be payable.',
        requirement: 'Application fee available or a plan to raise it',
        when: { eq: [{ fact: 'case.bankruptcyFeeArranged' }, { const: true }] },
        failMessage: 'The client cannot currently meet the application fee. Discuss how it will be raised.',
        severity: 'warning' },
    ],
    complianceRules: [],
  },

  // -------------------------------------------------------------------------
  {
    key: 'breathing-space',
    name: 'Breathing Space',
    description: 'Debt Respite Scheme moratorium: standard, or mental health crisis.',
    category: 'statutory-moratorium',
    jurisdictions: ['england-wales'],
    authority: 'Debt Respite Scheme (Breathing Space Moratorium and Mental Health Crisis Moratorium) (England and Wales) Regulations 2020',
    referenceFormat: 'BSP-{SEQ}',
    hasPaymentPlan: false,
    requiresCreditorApproval: false,
    reviewCadence: { everyMonths: null, description: 'Midway review required for a standard moratorium.' },
    stages: [
      { key: 'referral', name: 'Referral', order: 0, requiredEvidence: [],
        allowedNext: ['assessment', 'closed'], description: 'Request for a moratorium.', slaHours: 24,
        isAdvicePoint: false, isTerminal: false },
      { key: 'assessment', name: 'Assessment', order: 1,
        requiredEvidence: ['consent.processing', 'identity.verified', 'debts.captured'],
        allowedNext: ['advice', 'closed'], description: 'Eligibility and debt capture.', slaHours: 48,
        isAdvicePoint: false, isTerminal: false },
      { key: 'advice', name: 'Advice', order: 2, requiredEvidence: [],
        allowedNext: ['registered', 'closed'], description: 'Adviser records the decision to register.',
        slaHours: 24, isAdvicePoint: true, isTerminal: false },
      { key: 'registered', name: 'Registered', order: 3, requiredEvidence: [],
        allowedNext: ['midway-review', 'closed'], description: 'Moratorium registered; protections in force.',
        isAdvicePoint: false, isTerminal: false },
      { key: 'midway-review', name: 'Midway review', order: 4, requiredEvidence: [],
        allowedNext: ['registered', 'closed'], description: 'Required review of a standard moratorium.',
        slaHours: 72, isAdvicePoint: false, isTerminal: false },
      { key: 'closed', name: 'Ended', order: 5, requiredEvidence: [], allowedNext: [],
        description: 'Moratorium ended or cancelled.', isAdvicePoint: false, isTerminal: true },
    ],
    evidence: [
      ...CONSENT_AND_IDENTITY.filter((e) => e.key !== 'vulnerability.assessed'),
      { key: 'debts.captured', label: 'Qualifying debts captured', kind: 'declaration',
        description: 'The debts to be protected by the moratorium.', blocking: true },
      { key: 'mhc.evidence', label: 'Mental health crisis evidence', kind: 'document',
        description: 'Required only for a mental health crisis moratorium: evidence from an approved mental health professional.',
        blocking: false },
    ],
    eligibilityRules: [
      { key: 'no-active-insolvency', description: 'Cannot run alongside an insolvency procedure.',
        requirement: 'No active IVA, DRO or undischarged bankruptcy',
        when: { eq: [{ fact: 'history.hasActiveInsolvency' }, { const: false }] },
        failMessage: 'The client is in an active insolvency procedure and cannot enter Breathing Space.',
        severity: 'blocking', authority: 'Debt Respite Scheme Regulations 2020' },
      { key: 'not-used-recently', description: 'A standard moratorium cannot be repeated within 12 months.',
        requirement: 'No standard Breathing Space in the previous 12 months',
        when: { or: [{ eq: [{ fact: 'case.breathingSpaceType' }, { const: 'mental-health-crisis' }] },
                     { isNull: { fact: 'history.monthsSinceBreathingSpace' } },
                     { gte: [{ fact: 'history.monthsSinceBreathingSpace' }, { const: 12 }] }] },
        failMessage: 'A standard Breathing Space was used in the last 12 months. A mental health crisis moratorium may still be available.',
        severity: 'blocking', authority: 'Debt Respite Scheme Regulations 2020' },
      { key: 'mhc-evidence-present', description: 'A crisis moratorium needs evidence from an approved professional.',
        requirement: 'Evidence from an approved mental health professional, for a crisis moratorium',
        when: { or: [{ neq: [{ fact: 'case.breathingSpaceType' }, { const: 'mental-health-crisis' }] },
                     { eq: [{ fact: 'evidence.mhcEvidencePresent' }, { const: true }] }] },
        failMessage: 'A mental health crisis moratorium requires evidence from an approved mental health professional.',
        severity: 'blocking' },
    ],
    complianceRules: [],
  },

  // -------------------------------------------------------------------------
  {
    key: 'trust-deed',
    name: 'Protected Trust Deed',
    description: 'Scottish arrangement transferring estate to a trustee for creditors.',
    category: 'insolvency',
    jurisdictions: ['scotland'],
    authority: 'Bankruptcy (Scotland) Act 2016. Thresholds set by regulation - verify current limits.',
    referenceFormat: 'PTD-{SEQ}',
    hasPaymentPlan: true,
    requiresCreditorApproval: true,
    reviewCadence: { everyMonths: 12, description: 'Annual review by the trustee.' },
    stages: [
      ...commonStages('advice'),
      { key: 'advice', name: 'Advice', order: 3, requiredEvidence: [],
        allowedNext: ['granted', 'closed'], description: 'Regulated advice recorded by a competent adviser.',
        slaHours: 48, isAdvicePoint: true, isTerminal: false },
      { key: 'granted', name: 'Deed granted', order: 4, requiredEvidence: ['deed.signed'],
        allowedNext: ['protection', 'closed'], description: 'Trust deed granted and trustee appointed.',
        slaHours: 336, isAdvicePoint: false, isTerminal: false },
      { key: 'protection', name: 'Seeking protection', order: 5, requiredEvidence: [],
        allowedNext: ['live', 'closed'], description: 'Creditor notification period for protected status.',
        slaHours: 840, isAdvicePoint: false, isTerminal: false },
      { key: 'live', name: 'Protected', order: 6, requiredEvidence: [],
        allowedNext: ['review', 'arrears', 'closed'], description: 'Protected trust deed in force.',
        isAdvicePoint: false, isTerminal: false },
      { key: 'review', name: 'Annual review', order: 7, requiredEvidence: ['sfs.complete'],
        allowedNext: ['live', 'arrears', 'closed'], description: 'Annual review by the trustee.',
        slaHours: 336, isAdvicePoint: false, isTerminal: false },
      { key: 'arrears', name: 'Arrears', order: 8, requiredEvidence: [],
        allowedNext: ['live', 'closed'], description: 'Contributions missed.', slaHours: 72,
        isAdvicePoint: false, isTerminal: false },
      { key: 'closed', name: 'Closed', order: 9, requiredEvidence: [], allowedNext: [],
        description: 'Discharged or failed.', isAdvicePoint: false, isTerminal: true },
    ],
    evidence: [
      ...CONSENT_AND_IDENTITY, ...FINANCIAL_EVIDENCE,
      { key: 'deed.signed', label: 'Trust deed signed', kind: 'signature',
        description: 'Client signature on the trust deed.', blocking: true },
    ],
    eligibilityRules: [
      { key: 'scottish-resident', description: 'A trust deed is a Scottish remedy.',
        requirement: 'Client habitually resident in Scotland',
        when: { eq: [{ fact: 'client.jurisdiction' }, { const: 'scotland' }] },
        failMessage: 'A protected trust deed is only available to clients resident in Scotland.',
        severity: 'blocking' },
      { key: 'minimum-debt', description: 'A minimum level of debt applies.',
        requirement: 'Qualifying debt at or above the current minimum',
        when: { gte: [{ fact: 'debt.qualifyingPence' }, { fact: 'config.trustDeedMinimumDebtPence' }] },
        failMessage: 'Qualifying debt is below the minimum for a protected trust deed.',
        severity: 'blocking', authority: 'Bankruptcy (Scotland) Act 2016 - verify current minimum' },
      { key: 'sustainable-contribution', description: 'Contributions must be sustainable for the term.',
        requirement: 'A sustainable monthly contribution, or realisable assets',
        when: { or: [{ gte: [{ fact: 'affordability.sustainablePaymentPence' }, { const: 8000 }] },
                     { gt: [{ fact: 'assets.realisablePence' }, { const: 0 }] }] },
        failMessage: 'There is neither a sustainable contribution nor realisable estate. Consider sequestration or DAS.',
        severity: 'blocking' },
    ],
    complianceRules: [],
  },

  // -------------------------------------------------------------------------
  {
    key: 'sequestration',
    name: 'Sequestration',
    description: 'Scottish bankruptcy, including the Minimal Asset Process route.',
    category: 'insolvency',
    jurisdictions: ['scotland'],
    authority: 'Bankruptcy (Scotland) Act 2016. MAP bands set by regulation - verify current limits.',
    referenceFormat: 'SEQ-{SEQ}',
    hasPaymentPlan: false,
    requiresCreditorApproval: false,
    reviewCadence: { everyMonths: null, description: 'No periodic review.' },
    stages: [
      ...commonStages('advice'),
      { key: 'advice', name: 'Advice', order: 3, requiredEvidence: [],
        allowedNext: ['application', 'closed'], description: 'Regulated advice recorded by a competent adviser.',
        slaHours: 48, isAdvicePoint: true, isTerminal: false },
      { key: 'application', name: 'Application', order: 4, requiredEvidence: ['application.signed'],
        allowedNext: ['awarded', 'closed'], description: 'Application to the Accountant in Bankruptcy.',
        slaHours: 336, isAdvicePoint: false, isTerminal: false },
      { key: 'awarded', name: 'Awarded', order: 5, requiredEvidence: [],
        allowedNext: ['closed'], description: 'Sequestration awarded.', isAdvicePoint: false, isTerminal: false },
      { key: 'closed', name: 'Closed', order: 6, requiredEvidence: [], allowedNext: [],
        description: 'Discharged or refused.', isAdvicePoint: false, isTerminal: true },
    ],
    evidence: [
      ...CONSENT_AND_IDENTITY, ...FINANCIAL_EVIDENCE,
      { key: 'application.signed', label: 'Application approved by the client', kind: 'signature',
        description: 'Client confirmation of the application contents.', blocking: true },
    ],
    eligibilityRules: [
      { key: 'scottish-resident', description: 'Sequestration is a Scottish remedy.',
        requirement: 'Client habitually resident in Scotland',
        when: { eq: [{ fact: 'client.jurisdiction' }, { const: 'scotland' }] },
        failMessage: 'Sequestration is only available to clients resident in Scotland.', severity: 'blocking' },
      { key: 'map-eligibility', description: 'The Minimal Asset Process has its own debt and asset bands.',
        requirement: 'Within the MAP debt and asset bands, where MAP is the intended route',
        when: { or: [{ neq: [{ fact: 'case.sequestrationRoute' }, { const: 'map' }] },
                     { and: [
                       { between: [{ fact: 'debt.qualifyingPence' },
                                   { fact: 'config.mapMinimumDebtPence' },
                                   { fact: 'config.mapMaximumDebtPence' }] },
                       { lte: [{ fact: 'assets.totalPence' }, { fact: 'config.mapAssetLimitPence' }] }] }] },
        failMessage: 'The client falls outside the Minimal Asset Process bands. Consider full sequestration.',
        severity: 'blocking', authority: 'Bankruptcy (Scotland) Act 2016 - verify current bands' },
    ],
    complianceRules: [],
  },

  // -------------------------------------------------------------------------
  {
    key: 'das-dpp',
    name: 'Debt Arrangement Scheme (Debt Payment Programme)',
    description: 'Scotland\'s statutory debt management scheme, freezing interest and charges.',
    category: 'debt-management',
    jurisdictions: ['scotland'],
    authority: 'Debt Arrangement and Attachment (Scotland) Act 2002',
    referenceFormat: 'DAS-{SEQ}',
    hasPaymentPlan: true,
    requiresCreditorApproval: true,
    reviewCadence: { everyMonths: 12, description: 'Annual review of the programme.' },
    stages: [
      ...commonStages('advice'),
      { key: 'advice', name: 'Advice', order: 3, requiredEvidence: [],
        allowedNext: ['application', 'closed'], description: 'Regulated advice recorded by a competent adviser.',
        slaHours: 48, isAdvicePoint: true, isTerminal: false },
      { key: 'application', name: 'Application', order: 4, requiredEvidence: ['payment.mandate'],
        allowedNext: ['approved', 'closed'], description: 'Application submitted by an approved money adviser.',
        slaHours: 336, isAdvicePoint: false, isTerminal: false },
      { key: 'approved', name: 'Approved', order: 5, requiredEvidence: [],
        allowedNext: ['review', 'arrears', 'closed'], description: 'Programme approved and in payment.',
        isAdvicePoint: false, isTerminal: false },
      { key: 'review', name: 'Annual review', order: 6, requiredEvidence: ['sfs.complete'],
        allowedNext: ['approved', 'arrears', 'closed'], description: 'Annual review of the programme.',
        slaHours: 336, isAdvicePoint: false, isTerminal: false },
      { key: 'arrears', name: 'Arrears', order: 7, requiredEvidence: [],
        allowedNext: ['approved', 'closed'], description: 'Payments missed.', slaHours: 72,
        isAdvicePoint: false, isTerminal: false },
      { key: 'closed', name: 'Closed', order: 8, requiredEvidence: [], allowedNext: [],
        description: 'Completed or revoked.', isAdvicePoint: false, isTerminal: true },
    ],
    evidence: [
      ...CONSENT_AND_IDENTITY, ...FINANCIAL_EVIDENCE,
      { key: 'payment.mandate', label: 'Payment mandate in place', kind: 'payment-mandate',
        description: 'Payment arrangement to the payments distributor.', blocking: true },
    ],
    eligibilityRules: [
      { key: 'scottish-resident', description: 'DAS is a Scottish scheme.',
        requirement: 'Client habitually resident in Scotland',
        when: { eq: [{ fact: 'client.jurisdiction' }, { const: 'scotland' }] },
        failMessage: 'The Debt Arrangement Scheme is only available in Scotland.', severity: 'blocking' },
      { key: 'has-surplus', description: 'A programme needs a contribution.',
        requirement: 'A sustainable monthly contribution',
        when: { gte: [{ fact: 'affordability.sustainablePaymentPence' }, { const: 100 }] },
        failMessage: 'There is no sustainable surplus for a debt payment programme.', severity: 'blocking' },
      { key: 'two-or-more-debts', description: 'A programme covers two or more debts.',
        requirement: 'At least two debts',
        when: { gte: [{ fact: 'debt.count' }, { const: 2 }] },
        failMessage: 'A debt payment programme normally requires at least two debts.', severity: 'blocking' },
    ],
    complianceRules: [],
  },
] as const as readonly CaseTypeDefinition[];

/**
 * Default values for the statutory thresholds the rules reference. These are
 * tenant configuration: a firm updates them when a regulation changes, without
 * waiting for a release. They are deliberately expressed as facts rather than
 * baked into expressions so the same rule survives a change of limit.
 *
 * Verify every figure against the current regulations before use.
 */
export const DEFAULT_THRESHOLD_CONFIG: Record<string, number> = {
  'config.droDebtLimitPence': 5_000_000,
  'config.droAssetLimitPence': 200_000,
  'config.droSurplusLimitPence': 7_500,
  'config.droVehicleLimitPence': 400_000,
  'config.trustDeedMinimumDebtPence': 500_000,
  'config.mapMinimumDebtPence': 150_000,
  'config.mapMaximumDebtPence': 2_500_000,
  'config.mapAssetLimitPence': 200_000,
};
